language: java
jdk: openjdk11
os:
  - linux
branches:
  only:
  - dev
  - master
  except:
  - new_master
script: cd core && mvn -q clean install && cd jms-implementation && mvn -q clean package && cd target/interproscan-5-dist && cd $TRAVIS_BUILD_DIR && pwd && PATH=$TRAVIS_BUILD_DIR/core/jms-implementation/target/interproscan-5-dist:$PATH && echo $PATH && pwd && cd $TRAVIS_BUILD_DIR/core/jms-implementation/target/interproscan-5-dist && ls && which bin/ncoils/2.2.1/ncoils && ./interproscan.sh -i test_proteins.fasta -f tsv -dp
#./interproscan.sh -help
#./interproscan.sh -i test_proteins.fasta -f tsv -dp

notifications:  
  email:  
    recipients:  
    - nuka@ebi.ac.uk  
    on_success: always  
    on_failure: always
